version: '3.8'

services:


  db:
    image: postgres:latest
    environment:
        POSTGRES_DB: MyDb
        POSTGRES_USER: user123
        POSTGRES_PASSWORD: 123456789
    ports:
            - "5433:5432"  # Map your local port to the container's port
    volumes:
            - postgres-data:/var/lib/postgresql/data
    networks:
        - my-network  # Assign the web service to the same custom network
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"  # Map your local port to the container's port
    depends_on:
      - db
    volumes:
      - .:/var/www/html
    networks:
        - my-network  # Assign the web service to the same custom network

volumes:
  postgres-data:
networks:
    my-network:  # Define a custom network named my-network
        driver: bridge  # Use the bridge driver for simplicity


